// <auto-generated />
using System;
using Carrinho.Compra.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carrinho.Compra.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918175354_Criando as tabelas")]
    partial class Criandoastabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.CupomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CodigoCupom")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PercentualDesconto")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("CupomEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49e16d11-29ef-4dc2-8252-70e1603fd2b6"),
                            Ativo = true,
                            CodigoCupom = new Guid("1aeb24f1-5f02-41db-adfc-fb8e948ac9e3"),
                            PercentualDesconto = 10m
                        },
                        new
                        {
                            Id = new Guid("d37f362c-f1f6-4c84-92f6-2ff84cc62b63"),
                            Ativo = true,
                            CodigoCupom = new Guid("c7846571-6120-4543-9623-70c749b6f997"),
                            PercentualDesconto = 15m
                        });
                });

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.ItemCarrinhoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CarrinhoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensCarrinho");
                });

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.ProdutoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34d40ed5-a264-45c0-a8ec-825a2a08d9c7"),
                            Ativo = false,
                            DescricaoProduto = "Notebook Dell Inspiron",
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853",
                            PrecoLiquido = 3500.00m,
                            QuantidadeEstoque = 100
                        },
                        new
                        {
                            Id = new Guid("52942dc7-cccf-4769-bc19-a3816909f7f1"),
                            Ativo = false,
                            DescricaoProduto = "Smartphone Samsung Galaxy",
                            ImageUrl = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9",
                            PrecoLiquido = 1899.90m,
                            QuantidadeEstoque = 50
                        },
                        new
                        {
                            Id = new Guid("3d240408-514f-4801-a32e-05454b2edc85"),
                            Ativo = false,
                            DescricaoProduto = "Apple AirPods",
                            ImageUrl = "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434",
                            PrecoLiquido = 999.90m,
                            QuantidadeEstoque = 150
                        },
                        new
                        {
                            Id = new Guid("9d84926c-4fae-4b07-bb4f-27a5423dfaad"),
                            Ativo = false,
                            DescricaoProduto = "Teclado Mecânico",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
                            PrecoLiquido = 299.90m,
                            QuantidadeEstoque = 60
                        },
                        new
                        {
                            Id = new Guid("a50d352e-88bd-4ad3-9cb0-c6dbfbd1d981"),
                            Ativo = false,
                            DescricaoProduto = "Mouse Gamer",
                            ImageUrl = "https://images.unsplash.com/photo-1527814050087-3793815479db",
                            PrecoLiquido = 159.90m,
                            QuantidadeEstoque = 200
                        },
                        new
                        {
                            Id = new Guid("05fd5c1e-507c-4843-8956-369eb91e37e1"),
                            Ativo = false,
                            DescricaoProduto = "Monitor 24 Polegadas",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
                            PrecoLiquido = 899.90m,
                            QuantidadeEstoque = 30
                        },
                        new
                        {
                            Id = new Guid("497bc209-f13d-4488-b2ff-2e216a84def9"),
                            Ativo = false,
                            DescricaoProduto = "Smart TV 50 Polegadas",
                            ImageUrl = "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1",
                            PrecoLiquido = 2499.90m,
                            QuantidadeEstoque = 255
                        },
                        new
                        {
                            Id = new Guid("c5c5aefc-8a3e-450c-b7b4-028f20cbd1a9"),
                            Ativo = false,
                            DescricaoProduto = "Câmera Digital",
                            ImageUrl = "https://images.unsplash.com/photo-1516035069371-29a1b244cc32",
                            PrecoLiquido = 2199.90m,
                            QuantidadeEstoque = 30
                        },
                        new
                        {
                            Id = new Guid("23d7000e-32a7-44d0-b58f-5aa021eff66d"),
                            Ativo = false,
                            DescricaoProduto = "Console Gamer",
                            ImageUrl = "https://images.unsplash.com/photo-1606813907291-d86efa9b94db",
                            PrecoLiquido = 3999.90m,
                            QuantidadeEstoque = 50
                        },
                        new
                        {
                            Id = new Guid("fd9a47a1-882c-47d7-b181-c02252b30d0a"),
                            Ativo = false,
                            DescricaoProduto = "Headset Gamer",
                            ImageUrl = "https://images.unsplash.com/photo-1599669454699-248893623440",
                            PrecoLiquido = 349.90m,
                            QuantidadeEstoque = 60
                        });
                });

            modelBuilder.Entity("CarrinhoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CupomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CupomId");

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.ItemCarrinhoEntity", b =>
                {
                    b.HasOne("CarrinhoEntity", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carrinho.Compra.Domain.Entities.ProdutoEntity", "Produto")
                        .WithMany("ItensCarrinho")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CarrinhoEntity", b =>
                {
                    b.HasOne("Carrinho.Compra.Domain.Entities.CupomEntity", "Cupom")
                        .WithMany()
                        .HasForeignKey("CupomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cupom");
                });

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.ProdutoEntity", b =>
                {
                    b.Navigation("ItensCarrinho");
                });

            modelBuilder.Entity("CarrinhoEntity", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
