// <auto-generated />
using System;
using Carrinho.Compra.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carrinho.Compra.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.CarrinhoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CupomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CupomId");

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.CupomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CodigoCupom")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PercentualDesconto")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("CupomEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4525535d-d7cb-4c69-9c2c-3c82d760171d"),
                            Ativo = true,
                            CodigoCupom = new Guid("4838c500-9136-4a9c-bc68-f9e0f0f87e10"),
                            PercentualDesconto = 10m
                        },
                        new
                        {
                            Id = new Guid("43a2a5bd-f379-4558-8ac9-f637973fc154"),
                            Ativo = true,
                            CodigoCupom = new Guid("816b7d3b-c767-4451-af22-9deed1d6d846"),
                            PercentualDesconto = 15m
                        });
                });

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.ItemCarrinhoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarrinhoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensCarrinho");
                });

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.ProdutoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62caf4bd-82e9-4a1a-9878-563fd52093a2"),
                            DescricaoProduto = "Notebook Dell Inspiron",
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853",
                            PrecoLiquido = 3500.00m,
                            QuantidadeEstoque = 100
                        },
                        new
                        {
                            Id = new Guid("68fd356c-dc8d-4ab0-a936-d329a16af941"),
                            DescricaoProduto = "Smartphone Samsung Galaxy",
                            ImageUrl = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9",
                            PrecoLiquido = 1899.90m,
                            QuantidadeEstoque = 50
                        },
                        new
                        {
                            Id = new Guid("a426a272-8ec4-4fbf-8a5a-91e1b9664ff8"),
                            DescricaoProduto = "Apple AirPods",
                            ImageUrl = "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434",
                            PrecoLiquido = 999.90m,
                            QuantidadeEstoque = 150
                        },
                        new
                        {
                            Id = new Guid("ddb6ea84-fc8f-4ad3-be2a-06578cb6758e"),
                            DescricaoProduto = "Teclado Mecânico",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
                            PrecoLiquido = 299.90m,
                            QuantidadeEstoque = 60
                        },
                        new
                        {
                            Id = new Guid("c58b1bad-25f8-4a81-a62a-21887dec7228"),
                            DescricaoProduto = "Mouse Gamer",
                            ImageUrl = "https://images.unsplash.com/photo-1527814050087-3793815479db",
                            PrecoLiquido = 159.90m,
                            QuantidadeEstoque = 200
                        },
                        new
                        {
                            Id = new Guid("caaaa9ea-d3d6-4b4e-bc9b-6f8e212af08d"),
                            DescricaoProduto = "Monitor 24 Polegadas",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
                            PrecoLiquido = 899.90m,
                            QuantidadeEstoque = 30
                        },
                        new
                        {
                            Id = new Guid("3fc3aac5-9eff-4642-9bbb-75ff3e166efd"),
                            DescricaoProduto = "Smart TV 50 Polegadas",
                            ImageUrl = "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1",
                            PrecoLiquido = 2499.90m,
                            QuantidadeEstoque = 255
                        },
                        new
                        {
                            Id = new Guid("14ab4cf0-21c9-454e-acd1-6ca20bae3bc3"),
                            DescricaoProduto = "Câmera Digital",
                            ImageUrl = "https://images.unsplash.com/photo-1516035069371-29a1b244cc32",
                            PrecoLiquido = 2199.90m,
                            QuantidadeEstoque = 30
                        },
                        new
                        {
                            Id = new Guid("a0fd9874-2096-46d0-9ba4-23a386c21577"),
                            DescricaoProduto = "Console Gamer",
                            ImageUrl = "https://images.unsplash.com/photo-1606813907291-d86efa9b94db",
                            PrecoLiquido = 3999.90m,
                            QuantidadeEstoque = 50
                        },
                        new
                        {
                            Id = new Guid("876993eb-7f0d-4928-95b1-e0803b88707a"),
                            DescricaoProduto = "Headset Gamer",
                            ImageUrl = "https://images.unsplash.com/photo-1599669454699-248893623440",
                            PrecoLiquido = 349.90m,
                            QuantidadeEstoque = 60
                        });
                });

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.CarrinhoEntity", b =>
                {
                    b.HasOne("Carrinho.Compra.Domain.Entities.CupomEntity", "Cupom")
                        .WithMany()
                        .HasForeignKey("CupomId");

                    b.Navigation("Cupom");
                });

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.ItemCarrinhoEntity", b =>
                {
                    b.HasOne("Carrinho.Compra.Domain.Entities.CarrinhoEntity", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carrinho.Compra.Domain.Entities.ProdutoEntity", "Produto")
                        .WithMany("ItensCarrinho")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.CarrinhoEntity", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Carrinho.Compra.Domain.Entities.ProdutoEntity", b =>
                {
                    b.Navigation("ItensCarrinho");
                });
#pragma warning restore 612, 618
        }
    }
}
